### ISSUE TITLE
Which Banner

### ISSUE THREAD

**Issue by Zabrane** [NF02/pdfcomp#2]

**Comment by Zabrane** [comment]
Hi @NF02 
Thanks for `pdfcomp`. It really works as expected.
I'm intrigued by these [lines](https://github.com/NF02/pdfcomp/blob/main/pdfcomp#L98-L100).
How did you create this nice banner?

**Comment by NF02** [comment]
With an application called toilet, it has different fonts, it is used to create bunners in ascii, it is a very nice software available for Linux, Mac and BSD. While the tables are handmade, in fact, it took me some time

**Comment by Zabrane** [comment]
@NF02 Thanks. Which font did you use? It looks amazing

**Comment by Zabrane** [comment]
I found it:
```
┏━╸╻ ╻╺┳╸╻ ╻┏━┓┏━╸
┣╸ ┃ ┃ ┃ ┃ ┃┣┳┛┣╸
╹  ┗━┛ ╹ ┗━┛╹┗╸┗━╸
```

Many thanks
